server:
  port: 8181
spring:
  main:
    allow-circular-references: true #允许循环依赖
  servlet:
    multipart:
      max-file-size: 1024MB #上传文件大小限制
      max-request-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/move_house?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8
logging:
  level:
    com.movehouse: debug
file:
  upload-path: D:\Data\temp\moveHouseUploadFile
jwt:
  secret: 1234567890
  expire-hours: 168
